name: env_isaaclab
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.12.2=haa95532_0
  - expat=2.7.3=h885b0b7_3
  - libexpat=2.7.3=h885b0b7_3
  - libffi=3.4.4=hd77b12b_1
  - libzlib=1.3.1=h02ab6af_0
  - openssl=3.0.18=h543e019_0
  - pip=25.3=pyhc872135_0
  - python=3.11.14=h981015d_0
  - setuptools=80.9.0=py311haa95532_0
  - sqlite=3.51.0=hda9a48d_0
  - tk=8.6.15=hf199647_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py311haa95532_0
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - pip:
      - absl-py==2.3.1
      - aioboto3==15.1.0
      - aiobotocore==2.24.0
      - aiodns==3.1.1
      - aiofiles==23.2.1
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.11.11
      - aioitertools==0.11.0
      - aiosignal==1.3.2
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.12.0
      - asteval==1.0.6
      - asttokens==3.0.1
      - async-timeout==5.0.1
      - attrs==25.1.0
      - awscrt==0.23.8
      - azure-core==1.28.0
      - azure-identity==1.13.0
      - azure-storage-blob==12.17.0
      - boto3==1.39.11
      - botocore==1.39.11
      - certifi==2025.11.12
      - cffi==2.0.0
      - charset-normalizer==3.3.2
      - click==8.1.7
      - cloudpickle==3.1.2
      - colorama==0.4.6
      - comm==0.2.3
      - contourpy==1.3.1
      - coverage==7.4.4
      - cryptography==44.0.0
      - cycler==0.11.0
      - decorator==5.2.1
      - einops==0.8.1
      - executing==2.2.1
      - farama-notifications==0.0.4
      - fastapi==0.115.7
      - filelock==3.13.1
      - flaky==3.8.1
      - flatdict==4.0.1
      - fonttools==4.55.3
      - frozenlist==1.5.0
      - fsspec==2024.6.1
      - gitdb==4.0.12
      - gitpython==3.1.45
      - grpcio==1.76.0
      - gunicorn==23.0.0
      - gym==0.23.1
      - gym-notices==0.1.0
      - gymnasium==1.2.1
      - h11==0.16.0
      - h5py==3.15.1
      - hidapi==0.14.0.post2
      - httptools==0.6.1
      - huggingface-hub==0.36.0
      - hydra-core==1.3.2
      - idna==3.10
      - idna-ssl==1.1.0
      - imageio==2.37.0
      - imageio-ffmpeg==0.6.0
      - importlib-metadata==8.7.0
      - iniconfig==2.3.0
      - ipython==9.8.0
      - ipython-pygments-lexers==1.1.1
      - ipywidgets==8.1.5
      - isaaclab==0.49.0
      - isaaclab-assets==0.2.3
      - isaaclab-mimic==1.0.16
      - isaaclab-rl==0.4.4
      - isaaclab-tasks==0.11.9
      - isaacsim==5.1.0.0
      - isaacsim-app==5.1.0.0
      - isaacsim-asset==5.1.0.0
      - isaacsim-benchmark==5.1.0.0
      - isaacsim-code-editor==5.1.0.0
      - isaacsim-core==5.1.0.0
      - isaacsim-cortex==5.1.0.0
      - isaacsim-example==5.1.0.0
      - isaacsim-extscache-kit==5.1.0.0
      - isaacsim-extscache-kit-sdk==5.1.0.0
      - isaacsim-extscache-physics==5.1.0.0
      - isaacsim-gui==5.1.0.0
      - isaacsim-kernel==5.1.0.0
      - isaacsim-replicator==5.1.0.0
      - isaacsim-rl==5.1.0.0
      - isaacsim-robot==5.1.0.0
      - isaacsim-robot-motion==5.1.0.0
      - isaacsim-robot-setup==5.1.0.0
      - isaacsim-ros1==5.1.0.0
      - isaacsim-ros2==5.1.0.0
      - isaacsim-sensor==5.1.0.0
      - isaacsim-storage==5.1.0.0
      - isaacsim-template==5.1.0.0
      - isaacsim-test==5.1.0.0
      - isaacsim-utils==5.1.0.0
      - isodate==0.6.1
      - jedi==0.19.2
      - jinja2==3.1.6
      - jmespath==1.0.1
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - junitparser==4.0.2
      - jupyterlab-widgets==3.0.16
      - kiwisolver==1.4.4
      - llvmlite==0.42.0
      - markdown==3.10
      - markdown-it-py==4.0.0
      - markupsafe==2.1.3
      - matplotlib==3.10.3
      - matplotlib-inline==0.2.1
      - mdurl==0.1.2
      - ml-dtypes==0.5.4
      - moviepy==2.2.1
      - mpmath==1.3.0
      - msal==1.27.0
      - msal-extensions==1.0.0
      - msgpack==1.1.2
      - multidict==6.1.0
      - nest-asyncio==1.5.6
      - networkx==3.3
      - numba==0.59.1
      - numpy==1.26.0
      - oauthlib==3.2.2
      - omegaconf==2.3.0
      - onnx==1.20.0
      - onnx-ir==0.1.12
      - onnxscript==0.5.6
      - opencv-python-headless==4.11.0.86
      - orjson==3.11.5
      - osqp==0.6.7.post3
      - packaging==23.0
      - pandas==2.3.3
      - parso==0.8.5
      - pillow==11.3.0
      - pint==0.20.1
      - platformdirs==4.5.1
      - pluggy==1.6.0
      - portalocker==2.7.0
      - prettytable==3.3.0
      - proglog==0.1.12
      - prompt-toolkit==3.0.52
      - propcache==0.2.1
      - protobuf==6.33.2
      - psutil==5.9.8
      - pure-eval==0.2.3
      - pycares==4.8.0
      - pycparser==2.23
      - pydantic==2.11.10
      - pydantic-core==2.33.2
      - pyglet==1.5.31
      - pygments==2.19.2
      - pyjwt==2.10.1
      - pyparsing==3.0.9
      - pyperclip==1.8.0
      - pypng==0.20220715.0
      - pytest==9.0.2
      - pytest-mock==3.15.1
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.2.1
      - python-multipart==0.0.20
      - pytz==2024.1
      - pywin32==306
      - pyyaml==6.0.2
      - qdldl==0.1.7.post5
      - qrcode==7.4.2
      - ray==2.52.1
      - referencing==0.37.0
      - regex==2025.11.3
      - requests==2.32.3
      - requests-oauthlib==1.3.1
      - rich==14.2.0
      - rl-games==1.6.1
      - rpds-py==0.30.0
      - rsl-rl-lib==3.1.2
      - rtree==1.3.0
      - s3transfer==0.13.1
      - safetensors==0.7.0
      - scipy==1.15.3
      - sentry-sdk==2.29.1
      - setproctitle==1.3.7
      - six==1.17.0
      - skrl==1.4.3
      - smmap==5.0.2
      - stable-baselines3==2.7.1
      - stack-data==0.6.3
      - starlette==0.49.1
      - sympy==1.13.3
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.4
      - tensordict==0.9.0
      - tokenizers==0.22.1
      - toml==0.10.2
      - tomli==2.3.0
      - torch==2.7.0+cu128
      - torchaudio==2.7.0+cu128
      - torchvision==0.22.0+cu128
      - tornado==6.5.1
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.57.3
      - trimesh==4.5.1
      - typing-extensions==4.12.2
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - urllib3==2.6.0
      - uvicorn==0.29.0
      - wandb==0.23.1
      - warp-lang==1.10.1
      - watchdog==4.0.0
      - wcwidth==0.2.14
      - websockets==12.0
      - werkzeug==3.1.4
      - widgetsnbextension==4.0.15
      - wrapt==1.16.0
      - yarl==1.18.3
      - zipp==3.23.0
prefix: C:\Users\komin\anaconda3\envs\env_isaaclab
